let g:vim_config_dir = expand('<sfile>:p:h') . '/'
if !exists('g:vscode')
    exec 'source ' . g:vim_config_dir . 'plugins.vim'
endif

exec 'source ' . g:vim_config_dir . 'settings.vim'
exec 'source ' . g:vim_config_dir . 'mappings.vim'
if filereadable(g:vim_config_dir . 'local.vim')
    exec 'source ' . g:vim_config_dir . 'local.vim'
endif

